- name: "Sync hwclock"
  shell: hwclock --hctosys
- name: "Update packages"
  apt:
    update_cache: yes
    upgrade: full
    autoremove: yes
- name: "Install common packages"
  apt:
    state: present
    name:
    - bash-completion
    - bc
    - curl
    - dnsutils
    - dstat
    - git
    - htop
    - jq
    - locales
    - logrotate
    - moreutils
    - ncdu
    - netcat
    - parallel
    - pigz
    - pv
    - pv
    - rsync
    - screen
    - sqlite3
    - tmux
    - tree
    - tree
    - unzip
    - vim
    - wget
    - zstd
