- name: "Update packages"
  apt:
    update_cache: true
    upgrade: full
    autoremove: true
- name: "Install common packages"
  apt:
    state: present
    name:
      - bash-completion
      - bc
      - curl
      - dnsutils
      - dstat
      - git
      - htop
      - jq
      - locales
      - logrotate
      - moreutils
      - multitail
      - ncdu
      - netcat
      - parallel
      - pigz
      - pv
      - rsync
      - screen
      - sqlite3
      - tmux
      - tree
      - tree
      - unzip
      - vim
      - wget
      - zstd
