- name: "Ensure group labe exists"
  group:
    name: labe
    state: present

- name: "Create service worker"
  user:
    name: "labe"
    group: "labe"
    shell: "/bin/bash"
    create_home: true

- name: "Install ckit release"
  apt:
    deb: https://github.com/slub/labe/releases/download/v{{ ckit_version }}/ckit_{{ ckit_version }}_amd64.deb

- name: "Install labe release"
  apt:
    deb: https://github.com/slub/labe/releases/download/v{{ labe_version }}/labe_{{ labe_version}}_amd64.deb

- name: "Reread systemd unit files"
  systemd:
    daemon_reload: true

- name: "Change application log file ownership"
  ansible.builtin.file:
    path: /var/log/labe.log
    owner: labe
    group: labe
    state: touch
    mode: '0644'

- name: "Change access log file ownership"
  ansible.builtin.file:
    path: /var/log/labe-access.log
    owner: labe
    group: labe
    state: touch
    mode: '0644'

- name: "Change default data file ownership"
  ansible.builtin.file:
    path: /usr/share/labe/data
    owner: labe
    group: labe
    state: directory
    mode: '0755'

- name: "Setup logrotate"
  blockinfile:
    path: "/etc/logrotate.d/{{ item.path }}"
    block: "{{ item.conf }}"
    create: true
    mode: '0644'
  loop: "{{ lp_logrotate_confd }}"
  vars:
    lp_logrotate_confd:
      - path: labe
        conf: |
          /var/log/labe.log {
              daily
              rotate 3
              size 100M
              compress
              delaycompress
          }
      - path: labe-access
        conf: |
          /var/log/labe-access.log {
              daily
              rotate 3
              size 100M
              compress
              delaycompress
          }

- name: "Allow labe user to restart the labe server"
  lineinfile:
    path: /etc/sudoers
    state: present
    regexp: '^labe'
    line: 'labe ALL=(ALL:ALL) NOPASSWD: /usr/bin/systemctl restart labed'
    validate: visudo -cf %s

- name: "Set XDG_DATA_HOME system-wide"
  lineinfile:
    path: /etc/environment
    state: present
    regexp: "^XDG_DATA_HOME="
    line: "XDG_DATA_HOME=/usr/share"

- name: "Creates an entry like `PATH=/opt/bin:...` on top of crontab"
  cron:
    name: PATH
    user: labe
    env: true
    job: /usr/local/sbin:/usr/local/bin:/sbin:/bin:/usr/sbin:/usr/bin

- name: "Set shell of cron explicitly"
  cron:
    name: SHELL
    user: labe
    env: true
    job: /bin/bash

# Setup crontab for data updates. We squash the various steps into a one-liner:
# (a) delete obsolete artifacts, (b) run data updates, (c) restart the server,
# (d) warm cache.
#
# As of 01/2022, (b) takes about 3-4 hours, (d) maybe 1-2 hours.
#
# Note that changing the "cron.name" will add a new entry in crontab (may need
# to remove entries manually).
#
# The number of docs for cache warming is flexible, e.g. 150K items took about
# 90min to cache and caching can run easily in the background. Another data
# point, cache warmup with 200K takes 98min (with 32 threads); the resulting
# sqlite3 cache file is 9GB (values are about 20% of the size due to
# compression).
#
# May switch to systemd.timer version in the future.
- name: "Setup crontab for data updates, cleanups and cache warmup"
  cron:
    name: Data updates for labe, cleanups, cache warmup
    user: labe
    hour: "0"
    minute: "5"
    job: >
      rm -f $(labe.pyz --data-dir /usr/share/labe --list-deletable) &&
      labe.pyz --data-dir /usr/share/labe -r CombinedUpdate --workers 4 &&
      sudo systemctl restart labed &&
      zstd -qcd -T0 /usr/share/labe/data/OpenCitationsRanked/current |
          awk '{ print $2 }' |
          head -n 300000 |
          shuf |
          parallel -j 32 -I {} 'curl -sL "http://localhost:8000/doi/{}"' > /dev/null

- name: "Cleanup shiv temporary files"
  cron:
    name: Cleanup shiv temporary files
    user: labe
    special_time: monthly
    job: rm -rf /home/labe/.shiv
