- name: "Ensure group labe exists"
  group:
    name: labe
    state: present

- name: "Create service worker"
  user:
    name: "labe"
    group: "labe"
    createhome: no

- name: "Install ckit release"
  apt:
    deb: https://github.com/slub/labe/releases/download/v{{ ckit_version }}/ckit_{{ ckit_version }}_amd64.deb

- name: "Install labe release"
  apt:
    deb: https://github.com/slub/labe/releases/download/v{{ labe_version }}/labe_{{ labe_version}}_amd64.deb

- name: "Change logging file ownership"
  ansible.builtin.file:
    path: /var/log/labe.log
    owner: labe
    group: labe
    state: touch
    mode: '0644'

- name: "Change default data file ownership"
  ansible.builtin.file:
    path: /usr/share/labe
    owner: labe
    group: labe
    state: directory
    mode: '0755'

- name: "Setup logrotate"
  blockinfile:
    path: "/etc/logrotate.d/{{ item.path }}"
    block: "{{ item.conf }}"
    create: true
  loop: "{{ lp_logrotate_confd }}"
  vars:
    lp_logrotate_confd:
    - path: labe
      conf: |
        /var/log/labe.log {
            daily
            rotate 3
            size 200M
            compress
            delaycompress
        }

- name: "Creates an entry like `PATH=/opt/bin:...` on top of crontab"
  cron:
    name: PATH
    env: yes
    job: /usr/local/sbin:/usr/local/bin:/sbin:/bin:/usr/sbin:/usr/bin

- name: "Setup crontab for data updates"
  cron:
    name: Data updates for labe
    hour: "13"
    minute: "30"
    job: "rm -f $(/usr/local/bin/labe.pyz --data-dir /usr/share --list-deletable) && /usr/local/bin/labe.pyz --data-dir /usr/share -r CombinedUpdate --workers 4 && systemctl restart labed"
