- name: "Ensure group labe exists"
  group:
    name: labe
    state: present

- name: "Create service worker"
  user:
    name: "labe"
    group: "labe"
    shell: "/bin/bash"
    create_home: yes

- name: "Install ckit release"
  apt:
    deb: https://github.com/slub/labe/releases/download/v{{ ckit_version }}/ckit_{{ ckit_version }}_amd64.deb

- name: "Install labe release"
  apt:
    deb: https://github.com/slub/labe/releases/download/v{{ labe_version }}/labe_{{ labe_version}}_amd64.deb

- name: "Change logging file ownership"
  ansible.builtin.file:
    path: /var/log/labe.log
    owner: labe
    group: labe
    state: touch
    mode: '0644'

- name: "Change default data file ownership"
  ansible.builtin.file:
    path: /usr/share/labe
    owner: labe
    group: labe
    state: directory
    mode: '0755'

- name: "Setup logrotate"
  blockinfile:
    path: "/etc/logrotate.d/{{ item.path }}"
    block: "{{ item.conf }}"
    create: true
  loop: "{{ lp_logrotate_confd }}"
  vars:
    lp_logrotate_confd:
    - path: labe
      conf: |
        /var/log/labe.log {
            daily
            rotate 3
            size 200M
            compress
            delaycompress
        }

- name: "Allow labe user to restart the labe server"
  lineinfile:
    dest: /etc/sudoers
    state: present
    regexp: '^labe'
    line: 'labe ALL=(ALL:ALL) NOPASSWD: /usr/bin/systemctl restart labed'
    validate: visudo -cf %s

- name: "Creates an entry like `PATH=/opt/bin:...` on top of crontab"
  cron:
    name: PATH
    user: labe
    env: yes
    job: /usr/local/sbin:/usr/local/bin:/sbin:/bin:/usr/sbin:/usr/bin

- name: "Setup crontab for data updates"
  cron:
    name: Data updates for labe
    user: labe
    hour: "14"
    minute: "46"
    job: "rm -f $(/usr/local/bin/labe.pyz --data-dir /usr/share --list-deletable) && /usr/local/bin/labe.pyz --data-dir /usr/share -r CombinedUpdate --workers 4 && sudo /usr/bin/systemctl restart labed"
