- name: "Ensure group labe exists"
  group:
    name: labe
    state: present

- name: "Create service worker"
  user:
    name: "labe"
    group: "labe"
    shell: "/bin/bash"
    create_home: true

- name: "Install ckit release"
  apt:
    deb: https://github.com/slub/labe/releases/download/v{{ ckit_version }}/ckit_{{ ckit_version }}_amd64.deb

- name: "Install labe release"
  apt:
    deb: https://github.com/slub/labe/releases/download/v{{ labe_version }}/labe_{{ labe_version}}_amd64.deb

- name: "Reread systemd unit files"
  systemd:
    daemon_reload: true

- name: "Change application log file ownership"
  ansible.builtin.file:
    path: /var/log/labe.log
    owner: labe
    group: labe
    state: touch
    mode: '0644'

- name: "Change access log file ownership"
  ansible.builtin.file:
    path: /var/log/labe-access.log
    owner: labe
    group: labe
    state: touch
    mode: '0644'

- name: "Change default data file ownership"
  ansible.builtin.file:
    path: /usr/share/labe/data
    owner: labe
    group: labe
    state: directory
    mode: '0755'

- name: "Setup logrotate"
  blockinfile:
    path: "/etc/logrotate.d/{{ item.path }}"
    block: "{{ item.conf }}"
    create: true
    mode: '0644'
  loop: "{{ lp_logrotate_confd }}"
  vars:
    lp_logrotate_confd:
      - path: labe
        conf: |
          /var/log/labe.log {
              daily
              rotate 3
              size 100M
              compress
              delaycompress
          }
      - path: labe-access
        conf: |
          /var/log/labe-access.log {
              daily
              rotate 3
              size 100M
              compress
              delaycompress
          }

- name: "Allow labe user to restart the labe server"
  lineinfile:
    dest: /etc/sudoers
    state: present
    regexp: '^labe'
    line: 'labe ALL=(ALL:ALL) NOPASSWD: /usr/bin/systemctl restart labed'
    validate: visudo -cf %s

- name: "Creates an entry like `PATH=/opt/bin:...` on top of crontab"
  cron:
    name: PATH
    user: labe
    env: true
    job: /usr/local/sbin:/usr/local/bin:/sbin:/bin:/usr/sbin:/usr/bin

# Setup crontab for data updates. We squash the various steps into a one-liner:
# (a) delete obsolete artifacts, (b) run data updates, (c) restart the server,
# (d) warm cache.
#
# As of 01/2022, (b) takes about 3-4 hours, (d) maybe 1-2 hours.
- name: "Setup crontab for data updates, cleanups and cache warmup"
  cron:
    name: Data updates for labe, cleanups, cache warmup
    user: labe
    hour: "0"
    minute: "5"
    job: >
      rm -f $(labe.pyz --data-dir /usr/share/labe --list-deletable) &&
      labe.pyz --data-dir /usr/share/labe -r CombinedUpdate --workers 4 &&
      sudo systemctl restart labed &&
      zstd -qcd -T0 /usr/share/labe/data/OpenCitationsRanked/current | awk '{ print $2 }' | head -n 100000 | shuf | parallel -I {} 'curl -sL "http://localhost:8000/doi/{}"'

